# APIs

## Breakdown of the types

* RPC - _Remote Procedure Call_. Some types:
	* [XML-RPC](https://en.wikipedia.org/wiki/XML-RPC)
	* [JSON-RPC](https://en.wikipedia.org/wiki/JSON-RPC),
	example implementation: [js-jrpc][https://github.com/vphantom/js-jrpc]
* SOAP - _Simple Object Access Protocol_
* REST - _Representational State Transfer_

Each of the above use a:

* Data format: e.g., JSON
* Transport mechanism: e.g., HTTP

These attributes will be highlighted below for each API category.

## RPC

> * Data format: various, including JSON, XML
> * Transport mechanism: various

xxxx

## SOAP

> * Data format: XML
> * Transport mechanism: HTTP, SMTP

SOAP is a successor to `XML-RPC`, using XML for the data format.

SOAP maintains state on the server

The best part about SOAP is that it programatically defines the API.
That is, in machine readable XML, the definition for the API - it's
routes, parameters, and allowed operations - are all defined so
that machines can understand. This allows for client libraries to be
created programatically. This is one of the huge downsides of REST is
that they generally have no machine readable definition, such that
nearly all client libraries created for REST APIs are done by hand,
each one separately.

At the risk of being opinionated, SOAP is a technology that's on its way
out. Especially in the R world, the SOAP client that exists ([SSOAP](https://github.com/omegahat/SSOAP))
often doesn't work on various R versions and platforms. And no other
efforts are being made for another SOAP client.

## REST

> * Data format: various, most often JSON
> * Transport mechanism: HTTP

## Others

A few others worth mentioning:

* [GraphQL][grapqhl] - a Facebook product. Breaks from REST by introducing
the concept of defining the data you want back in your query, and the server
figures out how to get you that data. Whereas with REST you'd have a mental model
of what you want, and make various REST calls to get that data. GraphQL
isn't widely used, and there's currently no GraphQL clients for R.

[grapqhl]: http://graphql.org/
